### ISSUE TITLE
可以兼容一下azure接口形式吗？毕竟azure比较稳定

### ISSUE THREAD

**Issue by bipedalBit** [easychen/chatchan-dist#1]
openai接口的稳定商业化云服务在逐步向azure迁移，openai本身的接口稳定性略差。
看到没开源前端项目源码，粗暴反序列化js看了眼，只发现了openai的路由格式。
azure的openai接口文档看这里：https://learn.microsoft.com/zh-cn/azure/cognitive-services/openai/reference

另外，azure的免费账号白嫖额度也不少呢。

**Comment by easychen** [comment]
Azure的接口个人申请不下来，没法调试，先不支持了。
