### ISSUE TITLE
页面布局错误

### ISSUE THREAD

**Issue by dizhichao777** [easychen/chatchan-dist#14]
大佬你好，在服务器部署时出现了页面布局混乱，请问怎么解决？万分感谢！
![屏幕截图 2023-04-06 202404](https://user-images.githubusercontent.com/82986469/230378614-79e879a1-2690-49af-9f7e-57ed9c03508d.png)

**Comment by easychen** [comment]
你这个css应该没有载入进来，检查下设置。具体怎么搞你问问GPT

**Comment by dizhichao777** [comment]
好的，感谢大佬！
