### ISSUE TITLE
建议添加对Azure OpenAI API的支持

### ISSUE THREAD

**Issue by davidwu111** [easychen/chatchan-dist#15]
建议添加对Azure OpenAI API的支持

- 对于OpenAI无法正常访问的区域，Azure API 可以正常访问并且速度非常快。
- 对比OpenAI API， Azure只有一些小的改动。

参考 https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference

谢谢

**Comment by s544838371** [comment]
> 建议添加对Azure OpenAI API的支持
> 
> * 对于OpenAI无法正常访问的区域，Azure API 可以正常访问并且速度非常快。
> * 对比OpenAI API， Azure只有一些小的改动。
> 
> 参考 [learn.microsoft.com/en-us/azure/cognitive-services/openai/reference](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference)
> 
> 谢谢

可以在Easy大佬添加支持之前，先用cloudflare的workers转一下

**Comment by easychen** [comment]
chat酱是支持 azure 接口的，只是模型的部署名称需要按默认创建。

参考 https://github.com/easychen/api2d-js#change-log

**Comment by s544838371** [comment]
> chat酱是支持 azure 接口的，只是模型的部署名称需要按默认创建。
> 
> 参考 [easychen/api2d-js#change-log](https://github.com/easychen/api2d-js#change-log)

只需要输入终结点地址和密钥就行呗，有空试一下
