### ISSUE TITLE
超长内容易导致重复回答

### ISSUE THREAD

**Issue by q629988171** [easychen/chatchan-dist#22]
环境描述：Windows10，Chrome 112.0.5615.86（正式版本） （64 位）。
问题描述：在通过chat酱向chatgpt提问，如果回复的内容过长，容易出现重复回答，而且格式也会出现混乱。AI_EDU没有出现这样的问题。
API地址：https://openai.api2d.net
Max Tokens: 1000
发散度：0.1
超时：60
历史上下文数量：6

### chat酱对话
![chat酱-1681481360550](https://user-images.githubusercontent.com/2260447/232078552-aefb0328-a1a1-484d-9696-ee0e2e7b245b.png)

### AI_EDU 对话
![ai_edu](https://user-images.githubusercontent.com/2260447/232079463-c83c5784-754e-4c54-af10-629a84702913.png)

**Comment by easychen** [comment]
Chat酱只呈现内容，并没有修改返回结果的功能，所以多半是设置的参数（比如temperature等）不同导致的。你可以通过devtools查看接口通信的数据。

至于代码样式，大概率是因为token限制导致答案截断，所以渲染不成功
