### ISSUE TITLE
会考虑出手机版吗？

### ISSUE THREAD

**Issue by JeremiahLee11** [easychen/chatchan-dist#23]
因为在手机网页端和chatgpt交流很不方便，想要个能有聊天记录的手机客户端。不知道有没有机会搞一个。

**Comment by easychen** [comment]
手机版有一个单独的产品叫做 Bot郡 。 Google Play下载 https://play.google.com/store/apps/details?id=com.botjun.mobile.botjun_mobile  网盘下载   🔗https://share.weiyun.com/jXtYKbZS 🔑密码：chatok
