### ISSUE TITLE
设置的问题

### ISSUE THREAD

**Issue by yuntian123456** [easychen/chatchan-dist#25]
我下载压缩包直接用的本地浏览器打开，提前修改了default.json填入相应的参数，但浏览器打开显示的不是default.json里填的参数。。。是我的使用方法有哪里不对吗？

**Comment by easychen** [comment]
因为协议权限的问题，default配置不支持本地浏览器

![image](https://user-images.githubusercontent.com/1294760/232697313-4382e65e-62fd-4865-9505-37582a5b199b.png)
