### ISSUE TITLE
配置了default.json没用

### ISSUE THREAD

**Issue by CattleZoe** [easychen/chatchan-dist#26]
1、为什么配置了default.json没用（在VPS上部署的，用的HTTPS访问的），还提示要配置KEY，是不是我哪里搞错了
2、这次版本升级不支持azure的key了，上一个版本还支持不是sk开头的azure的key了

**Comment by FORMAT-qi** [comment]
需要用  koa 、express之类的 http-sever 方式启动，静态的不行

**Comment by FORMAT-qi** [comment]
> 1、为什么配置了default.json没用（在VPS上部署的，用的HTTPS访问的），还提示要配置KEY，是不是我哪里搞错了 2、这次版本升级不支持azure的key了，上一个版本还支持不是sk开头的azure的key了

需要用 koa 、express之类的 http-sever 方式启动，静态的不行

**Comment by liwenjun97** [comment]
docker 版default.json也没用

**Comment by Cayde23** [comment]
配置完成后清除一下浏览器缓存再打开网页试试

**Comment by CattleZoe** [comment]
最新版可以了，谢谢两位作者
