### ISSUE TITLE
对话会提示”发送请求失败，请OpenAPI Key是否正确或重试。“

### ISSUE THREAD

**Issue by Decwind** [easychen/chatchan-dist#29]
部署后web访问会报”发送请求失败，请OpenAPI Key是否正确或重试。“错误，但是账户余额又能正常看到，请问是哪里不对吗

**Comment by easychen** [comment]
下载最新的zip包试试。 原因看1.0.8的更新说明。

**Comment by Decwind** [comment]
> 下载最新的zip包试试。原因看1.0.8的更新说明。

谢谢大佬，更新已解决，没想到昨天部署的今天就更新了，实在抱歉。
