### ISSUE TITLE
错误：请求过于频繁，或者服务器连接过多，请稍后再试

### ISSUE THREAD

**Issue by whn3500079813** [easychen/chatchan-dist#32]
![image](https://user-images.githubusercontent.com/94180745/233899726-5826db89-9759-4159-b6c6-e03111cb4997.png)
F12查看接口显示
![image](https://user-images.githubusercontent.com/94180745/233899858-01f53108-8720-45fb-b445-ca02f902fb5c.png)

key和api的接口都是对的不知道为啥电脑没法使用，手机上配置key和反代的接口填的一模一样可以正常使用，电脑出现如上报错

**Comment by easychen** [comment]
电脑和手机都是一个网页，如果一个能用，说明程序是正常的，因此不太可能是程序的问题。请检查key和请求地址前后是否有多余的空格或者斜线。

**Comment by easychen** [comment]
另外，从报错信息看，错误是openai接口返回的，api key好像没有发送出去。
