### ISSUE TITLE
切换其他标签页或最小化浏览器，AI重新开始回答

### ISSUE THREAD

**Issue by hqc17** [easychen/chatchan-dist#38]
环境：MacOS 12.6，chat酱docker本地部署版，Chrome Version 113.0.5672.92 (Official Build) (x86_64)
问题：在AI回答的过程中，chrome切换到其它标签页，再切回chat酱的标签页，回答中断并再次从头开始生成（内容是一样的）。最小化chrome也会有同样情况。但如果是打开其他APP，不去动chrome，就可以正常一次生成完。

**Comment by easychen** [comment]
请试试 1.0.11 版本。

**Comment by hqc17** [comment]
> 请试试 1.0.11 版本。

Docker更新镜像后，容器内web文件夹下多了一层build目录，导致访问变成Forbidden了

**Comment by easychen** [comment]
> > 请试试 1.0.11 版本。
> 
> Docker更新镜像后，容器内web文件夹下多了一层build目录，导致访问变成Forbidden了。

修复了，再试试
