### ISSUE TITLE
可以增加一个一键复制功能吗

### ISSUE THREAD

**Issue by aguai778** [easychen/chatchan-dist#8]
可以增加一个一键复制功能吗
现在复制内容有些不方便

**Comment by easychen** [comment]
1.0.4 鼠标在对话上时，会出现一个小图标，点击可以直接复制Markdown。

<img width="613" alt="image" src="https://user-images.githubusercontent.com/1294760/230294270-eea4e4c1-321b-4389-9466-2152779ae9e2.png">

**Comment by aguai778** [comment]
谢谢
