### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by 0000070** [easychen/chatchan-dist#9]
Max Tokens，发散度，历史上下文数量，需要联系上下文的情况下，各设置多少最合适；

系统提示词和用户提示词的区别是？

为什么不可以全屏窗口呢；

能否增加暂停和重新生成按钮，，

**Comment by easychen** [comment]
① 
<img width="709" alt="image" src="https://user-images.githubusercontent.com/1294760/230320114-6c750f55-ee7d-40b5-a3dc-897f4b558a98.png">

② Mac可以全屏，Windows如果不可以的话，可能就是我用的打包软件默认不支持。
③ 不能暂停，只能取消。取消功能现在就有。重新生成暂时没有规划。

**Comment by 0000070** [comment]
ok，tks
&nbsp;


??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月6日(星期四) 下午4:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [easychen/chatchan-dist] 几个问题 (Issue #9)





 
①
 
 
② Mac可以全屏，Windows如果不可以的话，可能就是我用的打包软件默认不支持。
 ③ 不能暂停，只能取消。取消功能现在就有。重新生成暂时没有规划。

**Comment by easychen** [comment]
重新生成答案在 0.1.5 版本添加了，大概下周发布，可以留意下。
